//! Provider-neutral relay model.
//!
//! This is intentionally smaller than any provider DTO: unsupported fields
//! are rejected or recorded by [`LossReport`] instead of being smuggled
//! through as an untyped JSON envelope.

use serde::{Deserialize, Serialize};

use super::JsonData;

/// Google-documented placeholder for a synthetic non-Gemini tool history.
pub const GEMINI_SYNTHETIC_THOUGHT_SIGNATURE: &str = "context_engineering_is_the_way_to_go";

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Protocol {
    OpenAi,
    OpenAiResponses,
    Claude,
    Gemini,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FixtureKind {
    Request,
    Response,
    Stream,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Role {
    System,
    Developer,
    User,
    Assistant,
    Tool,
    Model,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CanonicalRequest {
    pub model: String,
    pub instructions: Vec<String>,
    pub messages: Vec<CanonicalMessage>,
    pub max_output_tokens: Option<u64>,
    pub temperature: Option<f64>,
    pub stream: bool,
    pub tools: Vec<CanonicalTool>,
    pub tool_choice: Option<CanonicalToolChoice>,
    pub options: RequestOptions,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct RequestOptions {
    pub top_p: Option<f64>,
    pub reasoning_effort: Option<String>,
    pub response_format: Option<JsonData>,
    pub parallel_tool_calls: Option<bool>,
    pub user: Option<JsonData>,
    pub store: Option<JsonData>,
    pub metadata: Option<JsonData>,
    pub stream_options: Option<JsonData>,
    pub top_logprobs: Option<i64>,
    pub safety_identifier: Option<JsonData>,
    pub prompt_cache_retention: Option<JsonData>,
    pub prompt_cache_key: Option<String>,
    pub service_tier: Option<String>,
    pub enable_thinking: Option<JsonData>,
    pub thinking_budget: Option<JsonData>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CanonicalMessage {
    pub role: Role,
    pub parts: Vec<CanonicalContent>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CanonicalContent {
    Text {
        text: String,
    },
    Image {
        url: String,
        detail: Option<String>,
    },
    ToolCall {
        id: String,
        name: String,
        arguments: String,
    },
    ToolResult {
        id: String,
        /// Function name from Gemini's `functionResponse`, when supplied.
        name: Option<String>,
        output: JsonData,
    },
    Reasoning {
        text: String,
    },
    /// Claude's signed thinking block.  This is deliberately not represented
    /// by [`Reasoning`]: the signature is an opaque validator token and must
    /// remain attached to the same ordered Part as its thinking text.
    ClaudeThinking {
        thinking: String,
        signature: Option<String>,
        model: Option<String>,
        provenance: OpaqueStateProvenance,
    },
    /// Claude's redacted thinking payload.  The bytes are opaque and may not
    /// be substituted with an ordinary reasoning summary.
    RedactedThinking {
        data: JsonData,
        model: Option<String>,
        provenance: OpaqueStateProvenance,
    },
    /// Provider-specific opaque state that must remain adjacent to the Part
    /// which carried it.  This is deliberately separate from reasoning text:
    /// a thought signature is an opaque validator token, not user-visible
    /// reasoning.
    ProviderState {
        state: OpaqueProviderState,
    },
}

/// Provenance of an opaque provider state value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OpaqueStateProvenance {
    /// Bytes received from a provider and retained without interpretation.
    Authentic,
    /// A compatibility value generated by the gateway for synthetic history.
    Synthetic,
}

/// Provider-neutral storage for opaque state such as Gemini thought
/// signatures.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpaqueProviderState {
    /// Provider that defined the state (for example, `google`).
    pub provider: String,
    /// Provider-defined state kind (for example, `thought_signature`).
    pub kind: String,
    /// Uninterpreted JSON value.  Gemini's authentic signature is a string,
    /// while `JsonData` keeps this type useful for future provider extensions.
    pub raw: JsonData,
    /// Whether this value came from a provider or was generated by us.
    pub provenance: OpaqueStateProvenance,
    /// Model family associated with the state, when known.
    pub model: Option<String>,
}

impl OpaqueProviderState {
    /// Creates an authentic Gemini thought signature state.
    pub fn authentic_gemini_thought_signature(signature: String, model: Option<String>) -> Self {
        Self {
            provider: "google".to_owned(),
            kind: "thought_signature".to_owned(),
            raw: JsonData::String(signature),
            provenance: OpaqueStateProvenance::Authentic,
            model,
        }
    }

    /// Creates the documented synthetic Gemini history signature.
    pub fn synthetic_gemini_thought_signature(model: Option<String>) -> Self {
        Self {
            provider: "google".to_owned(),
            kind: "thought_signature".to_owned(),
            raw: JsonData::String(GEMINI_SYNTHETIC_THOUGHT_SIGNATURE.to_owned()),
            provenance: OpaqueStateProvenance::Synthetic,
            model,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CanonicalTool {
    pub name: String,
    pub description: Option<String>,
    pub input_schema: JsonData,
    pub strict: Option<bool>,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CanonicalToolChoice {
    Auto,
    None,
    Required,
    Function { name: String },
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CanonicalResponse {
    pub id: String,
    pub model: String,
    pub created_at: i64,
    pub output: Vec<CanonicalContent>,
    pub finish_reason: Option<FinishReason>,
    pub usage: Option<TokenUsage>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FinishReason {
    Stop,
    Length,
    ToolCalls,
    ContentFilter,
    Cancelled,
    Error,
    Other,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct TokenUsage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub total_tokens: u64,
    pub cached_input_tokens: u64,
    pub reasoning_tokens: u64,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CanonicalStreamEvent {
    ResponseStart {
        id: String,
        model: String,
    },
    ContentStart {
        index: usize,
        kind: StreamContentKind,
    },
    TextDelta {
        index: usize,
        delta: String,
    },
    ReasoningDelta {
        index: usize,
        delta: String,
    },
    ToolCallStart {
        index: usize,
        id: String,
        name: String,
    },
    ToolArgumentsDelta {
        index: usize,
        delta: String,
    },
    ContentEnd {
        index: usize,
    },
    ResponseEnd {
        finish_reason: FinishReason,
        usage: Option<TokenUsage>,
        model: Option<String>,
    },
    Error {
        code: Option<String>,
        message: String,
    },
    Cancelled,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StreamContentKind {
    Text,
    ToolCall,
    Reasoning,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct LossReport {
    pub dropped_fields: Vec<&'static str>,
    pub normalized_fields: Vec<&'static str>,
    pub synthetic_fields: Vec<&'static str>,
}

impl LossReport {
    pub fn is_lossless(&self) -> bool {
        self.dropped_fields.is_empty()
            && self.normalized_fields.is_empty()
            && self.synthetic_fields.is_empty()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Converted<T> {
    pub value: T,
    pub loss: LossReport,
}
